config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("django_beginnings.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^blog/', include("django_beginnings.blog.urls", namespace="blog")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

django_beginnings/blog/urls.py
from django.conf.urls import url

from .views import BlogList, BlogDetail, CommentForm

urlpatterns = [
    url(r'^$', BlogList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', BlogDetail.as_view(), name='detail'),
    #url(r'^(?P<pk>[0-9]+)/comment/$', CommentForm.as_view(), name='create_comment'),
]

django_beginnings/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(regex=r'^$', view=views.UserListView.as_view(), name='list'),

    # URL pattern for the UserRedirectView
    url(regex=r'^~redirect/$', view=views.UserRedirectView.as_view(), name='redirect'),

    # URL pattern for the UserDetailView
    url(regex=r'^(?P<username>[\w.@+-]+)/$', view=views.UserDetailView.as_view(), name='detail'),

    # URL pattern for the UserUpdateView
    url(regex=r'^~update/$', view=views.UserUpdateView.as_view(), name='update'),
]

django_beginnings/blog/models.py
from django.db import models
from django_beginnings.users.models import User

# Create your models here.

class BlogPost(models.Model):

    author = models.ForeignKey(User)
    title = models.CharField(max_length=500)
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class BlogComment(models.Model):

    author = models.ForeignKey(User)
    blogpost = models.ForeignKey(BlogPost)
    comment = models.CharField(max_length=140)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

django_beginnings/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.db import models
# from django.utils.translation import ugettext_lazy as _

class User(AbstractUser):

    def __unicode__(self):
        return self.username

    twitter_followers = models.BigIntegerField(default=0)
    instagram_followers = models.BigIntegerField(default=0)

    def get_total_followers(self):
        return self.twitter_followers + self.instagram_followers

django_beginnings/blog/forms.py
from django.forms import ModelForm
from .models import BlogComment

class CommentForm(ModelForm):

    class Meta:
        model = BlogComment
        fields = ('comment',)

    def is_valid(self):
        return True

django_beginnings/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

django_beginnings/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse

# Create your views here.
from .models import BlogPost, BlogComment
from braces.views import LoginRequiredMixin
from .forms import CommentForm
from django_beginnings.users.models import User

class BlogList(ListView):
    model = BlogPost


class BlogDetail(LoginRequiredMixin, DetailView):
    model = BlogPost

    def get_context_data(self, **kwargs):
        context = super(BlogDetail, self).get_context_data(**kwargs)
        context['form'] = CommentForm()

        return context

    def post(self, request, *args, **kwargs):
        self.form = CommentForm(request.POST)
        if self.form.is_valid():
            comment = self.form.save(commit=False)
            #print(dir(self.object))
            comment.author = User.objects.get(username = self.request.user.username)
            comment.blogpost = self.get_object()
            comment.save()
            return super(BlogDetail, self).get(request, *args, **kwargs)
        else:
            return super(BlogDetail, self).post(request, *args, **kwargs)

class CommentList(ListView):
    model = BlogComment

django_beginnings/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin


from .forms import UserForm
from .models import User


import tweepy
from instagram.client import InstagramAPI
from allauth.socialaccount.models import SocialAccount

def get_twitter_follower_count(user):
    auth = tweepy.OAuthHandler('08OKIFS5pnBFYULL8duPsTvkd', 'QvoNYSyTWsbzJLZiBFiUDn7U2rzb4ms2qLjfDLBmyl7So7PYa9')
    api = tweepy.API(auth)
    twitter_uid_list = SocialAccount.objects.filter(user_id=user.id, provider='twitter')
    if(len(twitter_uid_list) > 0):
        user.twitter_followers = api.get_user(twitter_uid_list[0].uid).followers_count
        user.save()

def get_instagram_follower_count(user):
    api = InstagramAPI(client_id='13245ce01c854900a3a964b9bdd964c5', client_secret='ed11480527dc4f6d959bc2fde47d25da')
    instagram_uid_list = SocialAccount.objects.filter(user_id=user.id, provider='instagram')
    if(len(instagram_uid_list) > 0):
        user.instagram_followers = api.user(instagram_uid_list[0].uid).counts['followed_by']
        user.save()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        get_twitter_follower_count(self.get_object())
        get_instagram_follower_count(self.get_object())
        return super(UserDetailView, self).get(request, *args, **kwargs)

class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

django_beginnings/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}djangotut{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <div class="header navbar">
      <div class="container">
        <a class="navbar-brand" href="/">djangotut</a>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'blog:list' %}">Blog</a></li>

          {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
            <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>
 

django_beginnings/templates/blog/blogcomment_form.html
{% extends "blogpost_detail.html" %}

{% block commentform %}
<form action="/blog/create/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit Comment" />
</form>
{% endblock %}

django_beginnings/templates/blog/blogcomment_list.html
{% extends blogpost_detail %}

django_beginnings/templates/blog/blogpost_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ object.title }}</h2>
    <h4>by {{ object.author }}</h4>
    <p>
    {{ object.text }}
    </p>
    <p><i>{{ object.date_posted }}</i></p>
    <br /><br />

    {% block commentform %}
        <form action={{ request.path }} method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit Comment" />
        </form>
    {% endblock %}

    <br />
    {% block comments %}
        <p>{{ object.blogcomment_set.count }} comments:</p>
        {% for comment in object.blogcomment_set.all %}
            <p>{{ comment.comment }} - <b>{{ comment.author }}</b> - <i>{{ comment.date_posted }}</i></p>
        {% endfor %}
    {% endblock %}



    <p> <a href="{% url 'blog:list' %}"> &lt;----- Back! </a> </p>
{% endblock %}

django_beginnings/templates/blog/blogpost_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Blog Posts!</h2>
    <ul>
        {% for post in object_list %}
            <li><a href="{%  url 'blog:detail' post.pk %}"><b>{{ post.title }}</b> by {{ post.author }} on <i>{{ post.date_posted }}</i></a></li>
        {% endfor %}
    </ul>
{% endblock %}

django_beginnings/templates/pages/about.html
{% extends "base.html" %}

django_beginnings/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <p>Welcome to my new site! Enjoy yourself!</p>

    <p>Maybe check out the <a href="{% url 'blog:list' %}">Blog!</a> </p>
{% endblock %}

django_beginnings/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->

    <br/><br/>
    {% load socialaccount %}
    <a class="btn btn-primary" href="{% provider_login_url "facebook" process="connect" %}">Connect your Facebook</a>
    <a class="btn btn-primary" href="{% provider_login_url "twitter" process="connect" %}">Connect your Twitter</a>
    <a class="btn btn-primary" href="{% provider_login_url "instagram" process="connect" %}">Connect your Instagram</a>

    <!-- End Action buttons -->
{% endif %}
    <br/><br/>

    <img src="{{user.socialaccount_set.all.0.get_avatar_url}}" height="100" width="100" />
    <img src="{{user.socialaccount_set.all.1.get_avatar_url}}" height="100" width="100" />
    <img src="{{user.socialaccount_set.all.2.get_avatar_url}}" height="100" width="100" />

    <br /><br/>

    Twitter Followers: {{ user.twitter_followers }} <br/>
    Instagram Followers: {{ user.instagram_followers }}<br/>
    Total Followers: {{ user.get_total_followers }} <br/>



    <br /><br/>

  </div>

</div>


</div>
{% endblock content %}

django_beginnings/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}User: {{ user.username }}{% endblock %}</h1>
            <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Update</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

django_beginnings/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

  <div class="row">
    <div class="col-xs-12">
      <h2>Users</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="list-group">
          {% for user in user_list %}
            <a href="{% url 'users:detail' user.username %}" class="list-group-item">
              <h4 class="list-group-item-heading">{{ user.username }}</h4>
              <p class="list-group-item-text">{{ maker.tagline }}</p>
            </a>
          {% endfor %}

      </div>
    </div>
  </div>

</div>

{% endblock content %}